image: gitpod/workspace-dotnet:latest
tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
#     dotnet run
ports:
  - port: 7283
    onOpen: open-preview
vscode:
  extensions:
    - muhammad-sammy.csharp
