image: gitpod/workspace-dotnet:latest
# tasks:
#   - name: Restore & Build
#     init: |
#       dotnet dev-certs https 
#       dotnet restore
#       dotnet build
# ports:
#   - port: 8000
#     onOpen: open-preview
vscode:
  extensions:
    - muhammad-sammy.csharp
